import os
import shutil
from datetime import datetime
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from app.db.models import Base, Order, Payment, BankSMS, CustomerRiskProfile
from PIL import Image, ImageDraw
from fastapi.testclient import TestClient
from app.main import app

DATABASE_URL = "sqlite:///./bank_payments.db"
UPLOAD_DIR = "uploads"
SEED_DIR = "seed_images"

os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(SEED_DIR, exist_ok=True)

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine)

def reset_db():
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)

def create_mock_slip(filename: str, amount: str, ref_id: str, date: str, blur: bool = False):
    img = Image.new('RGB', (400, 600), color=(255, 255, 255))
    d = ImageDraw.Draw(img)
    d.rectangle([(0, 0), (400, 80)], fill=(0, 51, 102))
    d.text((120, 30), "BANK OF MOCK", fill=(255, 255, 255))
    
    d.text((40, 150), "Payment Receipt", fill=(0, 0, 0))
    d.text((40, 200), f"Date: {date}", fill=(0, 0, 0))
    d.text((40, 250), f"Amount: {amount}", fill=(0, 0, 0))
    d.text((40, 300), f"Ref ID: {ref_id}", fill=(0, 0, 0))
    d.text((40, 350), "To: MOCK CORP INC", fill=(0, 0, 0))
    d.text((40, 400), "A/C: 987654321", fill=(0, 0, 0))
    
    if blur:
        img = img.resize((100, 150)).resize((400, 600))
        
    path = os.path.join(SEED_DIR, filename)
    img.save(path)
    return path

def seed():
    reset_db()
    db = SessionLocal()
    client = TestClient(app)
    
    now = datetime.utcnow()
    
    orders_data = [
        {"id": "ORD-001", "name": "Alice", "amount": 25000.0, "phone": "+94771234001"},
        {"id": "ORD-002", "name": "Bob", "amount": 15000.0, "phone": "+94771234002"},
        {"id": "ORD-003", "name": "Charlie", "amount": 10000.0, "phone": "+94771234003"},
        {"id": "ORD-004", "name": "David", "amount": 5000.0, "phone": "+94771234004"},
        {"id": "ORD-005", "name": "Eve", "amount": 20000.0, "phone": "+94771234005"},
        {"id": "ORD-006", "name": "Frank", "amount": 30000.0, "phone": "+94771234006"},
        {"id": "ORD-007", "name": "Grace", "amount": 8000.0, "phone": "+94771234007"},
        {"id": "ORD-008", "name": "Hank", "amount": 12000.0, "phone": "+94771234008"},
    ]
    
    for o in orders_data:
        order = Order(
            id=o["id"], customer_id=o["id"].replace("ORD-", "CUST-"),
            customer_name=o["name"], phone=o["phone"], expected_amount=o["amount"]
        )
        db.add(order)
    
    # Pre-add SMS Evidence
    sms1 = BankSMS(sender="BANK", raw_text="Received LKR 25000.00 Ref TXN100001", amount=25000.0, ref_id="TXN100001")
    sms8 = BankSMS(sender="BANK", raw_text="Received LKR 10000.00 Ref TXN100008", amount=10000.0, ref_id="TXN100008")
    db.add_all([sms1, sms8])
    db.commit()
    
    scenarios = [
        ("slip1.jpg", "ORD-001", "25,000.00", "TXN100001", False, "Normal Valid"),
        ("slip2.jpg", "ORD-002", "10,000.00", "TXN100002", False, "Wrong Amount"),
        ("slip3.jpg", "ORD-003", "10,000.00", "TXN100003", False, "Wrong Account"),
        ("slip4.jpg", "ORD-004", "5,000.00", "TXN100004", False, "Duplicate 1"),
        ("slip5.jpg", "ORD-005", "5,000.00", "TXN100004", False, "Duplicate 2 (Resized)"),
        ("slip6.jpg", "ORD-006", "30,000.00", "TXN100001", False, "Reused ID"),
        ("slip7.jpg", "ORD-007", "8,000.00", "TXN100007", True, "Blurry Slip"),
        ("slip8.jpg", "ORD-008", "12,000.00", "TXN100008", False, "Conflicting Evidence"),
    ]
    
    for img_name, order_id, amt, ref, blur, desc in scenarios:
        if desc == "Duplicate 2 (Resized)":
             img = Image.open(os.path.join(SEED_DIR, "slip4.jpg"))
             path = os.path.join(SEED_DIR, img_name)
             img.crop((10, 10, 390, 590)).save(path)
        else:
             path = create_mock_slip(img_name, amt, ref, now.strftime("%Y-%m-%d"), blur)
             
        print(f"Processing: {desc}...")
        with open(path, "rb") as f:
            client.post("/api/v1/submit-payment", data={"order_id": order_id}, files={"image": (img_name, f, "image/jpeg")})

    print(f"Seed data generation & pipeline testing complete!")
    
    # Print customer risk profiles generated by pipeline
    profiles = db.query(CustomerRiskProfile).order_by(CustomerRiskProfile.risk_score.desc()).all()
    print(f"\n--- Customer Risk Profiles ({len(profiles)}) ---")
    for p in profiles:
        print(f"  {p.customer_name}: {p.risk_level} (score={p.risk_score:.2f}, "
              f"submissions={p.total_submissions}, approved={p.approved_count}, rejected={p.rejected_count})")
    
    # Print ELA data summary
    all_payments = db.query(Payment).all()
    ela_count = sum(1 for p in all_payments if p.ela_image_path)
    print(f"\n--- ELA Analysis: {ela_count}/{len(all_payments)} payments have ELA heatmaps ---")
    for p in all_payments:
        if p.ela_score is not None:
            print(f"  Payment #{p.id} ({p.order_id}): ELA score={p.ela_score:.1f}")

if __name__ == "__main__":
    seed()
